inherit_from: .rubocop_todo.yml

require:
  - ./.rubocop/cataract/ban_assert_includes.rb

plugins:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'test/fixtures/**/*'
    - '**/*.so'
    - '**/*.bundle'

# extconf.rb uses standard Ruby C extension global variables ($CFLAGS, etc.)
Style/GlobalVars:
  Exclude:
    - 'ext/**/extconf.rb'

# Disable complexity metrics - too subjective and often leads to harder-to-read code
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

# Block nesting in byte-level parsers reflects CSS structure, not complexity
# Extracting helper methods would add method dispatch overhead in hot path
Metrics/BlockNesting:
  Exclude:
    - 'lib/cataract/pure/**/*.rb'

# Keep line length for tests disabled - long test strings are fine
Layout/LineLength:
  Exclude:
    - 'benchmarks/**/*'
    - 'test/**/*'
    - 'scripts/**/*'
    - '*.gemspec'
  AllowedPatterns:
    - '^\s*#'  # Allow long comment lines

# Allow more assertions per test - strict limit is too restrictive
Minitest/MultipleAssertions:
  Max: 10

# Disable ambiguous block association warnings in tests
# Tests frequently use assert/refute with blocks that call methods with their own blocks,
# e.g., `assert sheet.rules.any? { |r| r == '.box { color: red; }' }`
# This compares Rule objects against CSS strings using our custom Rule#== implementation.
# While this triggers the ambiguous block warning, it's intentional and clear in context.
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'test/**/*'

Style/Documentation:
   Enabled: false

# Disable modifier if/unless enforcement - use it when it's clearer, not because a cop says so
Style/IfUnlessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'test/**/*'

# Allow numbers in test method names - they represent actual values being tested
Naming/VariableNumber:
  Exclude:
    - 'test/**/*'

Naming/PredicatePrefix:
  Exclude:
    - 'lib/**/*.rb'

# Performance-critical hot path exclusions for lib/cataract/pure
# These cosmetic style rules add overhead via method dispatch or allocation

# Disable numeric predicates in hot path - method dispatch overhead
# Benchmark shows `> 0` is faster than `.positive?` due to avoiding method call
Style/NumericPredicate:
  Exclude:
    - 'lib/cataract/pure/**/*.rb'

# Disable multiple comparison style - avoid array allocation
# `||` chain is faster than `Array#include?` which allocates an array
Style/MultipleComparison:
  Exclude:
    - 'lib/cataract/pure/**/*.rb'

# Disable zero-length predicate in hot path - method dispatch overhead
# Direct comparison `.length > 0` is faster than `.empty?` method call
Style/ZeroLengthPredicate:
  Exclude:
    - 'lib/cataract/pure/**/*.rb'

# Benchmarked range vs offsets. Range has to allocated
# so not ideal in the hot path
Style/SlicingWithRange:
  Exclude:
    - 'lib/cataract/pure/**/*.rb'

# Disable modifier while/until style in parsing code - readability
# Byte-level parsing loops are clearer with traditional while...end form
# Example: `while i < len && ident_char?(selector.getbyte(i)); i += 1; end`
# is more readable than `i += 1 while i < len && ident_char?(selector.getbyte(i))`
Style/WhileUntilModifier:
  Exclude:
    - 'lib/cataract/pure/**/*.rb'

# Disable between? suggestion in hot path - method dispatch overhead
# Benchmark shows `byte >= X && byte <= Y` is 2.60-4.82x faster than `.between?(X, Y)`
Style/ComparableBetween:
  Exclude:
    - 'lib/cataract/pure/**/*.rb'

# Disable map suggestion for array building - performance
# Benchmark shows `each { arr << x }` is 1.05-1.11x faster than `arr = map { x }`
# The << pattern is faster than map's implicit array return (even without YJIT)
Style/MapIntoArray:
  Exclude:
    - 'lib/cataract/pure/**/*.rb'

Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/cataract/pure/**/*.rb'

Style/StderrPuts:
  Exclude:
    - 'scripts/**/*.rb'

# Disable all performance cops in tests - test clarity is more important than micro-optimizations
# Performance suggestions often hurt readability without meaningful benefit in test code
Performance:
  Exclude:
    - 'test/**/*'

Style/HashLikeCase:
  Exclude:
    - 'benchmarks/**/*'

# Custom Cataract cops
Cataract/BanAssertIncludes:
  Enabled: true
  Include:
    - 'test/**/*'
  Exclude:
    - 'test/test_benchmark_doc_generator.rb'
    - 'test/support/**/*'  # Support files define assert_contains which uses assert_includes internally
