# frozen_string_literal: true

require 'mkmf'
require 'fileutils'

# Shared by both extconf.rb files.
#
# `gem install cataract -- --disable-native-extension` installs the pure Ruby
# backend on its own, for hosts with no compiler. Both extensions honour the
# flag, and the decision has to reach runtime, which is what the generated
# build config carries.
module ExtensionConfig
  # Written into the installed gem's lib/, alongside the code that reads it.
  GENERATED_CONFIG = File.expand_path('../../lib/cataract/build_config.rb', __dir__)

  module_function

  def native_extension?
    enable_config('native-extension', true)
  end

  # RubyGems calls a build failed whenever extconf leaves no Makefile, so
  # opting out still has to write one. It needs every target the install
  # invokes; each does nothing.
  def write_stub_makefile
    File.write('Makefile', <<~MAKE)
      all install static install-so install-rb clean:
      \t@true
      .PHONY: all install static install-so install-rb clean
    MAKE
  end

  # Records which backend this install has, for lib/cataract.rb to read.
  # Written on both paths so re-enabling the extension overwrites a stale
  # opt-out rather than leaving the library pointed at pure Ruby.
  def write_build_config(native:)
    FileUtils.mkdir_p(File.dirname(GENERATED_CONFIG))
    File.write(GENERATED_CONFIG, <<~RUBY)
      # frozen_string_literal: true

      # Generated by ext/cataract/extconf.rb at build time. Do not edit.
      module Cataract
        module BuildConfig
          # False when installed with --disable-native-extension.
          NATIVE_EXTENSION = #{native}
        end
      end
    RUBY
  end

  # Called first by both extconf files. Returns false when the caller should
  # stop without building.
  def build_native_extension?
    if native_extension?
      write_build_config(native: true)
      return true
    end

    puts 'Native extension: DISABLED (--disable-native-extension) - installing pure Ruby only'
    write_build_config(native: false)
    write_stub_makefile
    false
  end
end
